### PR TITLE
1.0.4

### PR DESCRIPTION
**Pull request by joemaller**
Bump package.json to 1.0.4 so npm can pull the updated version. ref #24

### CODE REVIEW

**Comment by riccardoscalco** [comment]
Thanks again, and sorry for the latency.

**Comment by joemaller** [comment]
No problem at all. Do you know what else we need to do to get npm.com to see the updated version? @riccardoscalco

**Comment by joemaller** [comment]
Looks like you need to run `npm publish`. 

https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package

**Comment by riccardoscalco** [comment]
ok, done.

**Pull request merged**
