### PR TITLE
add packagejson and publish to npm

### PR DESCRIPTION
**Pull request by maxogden**
Hi, I wanted to use this with http://browserify.org/, so I added a package.json and published it to npm here: https://www.npmjs.com/textures

It doesn't look like you have an npm account (https://www.npmjs.com/~riccardoscalco), but if you get one I would be happy to add you as an owner to the npm package so you can publish updates. Otherwise I'm happy to do so

Here's an example of why this functionality is useful (self contained programs): http://requirebin.com/?gist=cc20dd615f6b703cd9aa

### CODE REVIEW

**Comment by KingScooty** [comment]
+1

**Comment by KingScooty** [comment]
Actually, should d3 be listed as a dependency?

**Comment by riccardoscalco** [comment]
Well done. Now I have an npm account (https://www.npmjs.com/~riccardoscalco), thanks for the help.

**Comment by bollwyvl** [comment]
On npm, a lenient peerDependency may be more accurate, as nobody needs 50 copies of d3 running around deep in the wilds of node_modules:

```json
"peerDependencies": {
  "d3": "3.x"
}
```

A downstream user would still have to specify d3 as a dependency of their project, as soon peered deps won't be installed by default!

**Comment by maxogden** [comment]
d3 isn't really designed to be used as a module, but rather as a page
global, so in this case I would not recommend listing it in package.json in
any way

On Thursday, March 19, 2015, bollwyvl <notifications@github.com> wrote:

> On npm, a lenient peerDependency may be more accurate, as nobody needs 50
> copies of d3 running around deep in the wilds of node_modules:
>
> "peerDependencies": {
>   "d3": "3.x"
> }
>
> A downstream user would still have to specify d3 as a dependency of their
> project, as soon peered deps won't be installed by default!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/riccardoscalco/textures/pull/8#issuecomment-83590185>.
>


-- 
Sent from my phone

**Comment by bollwyvl** [comment]
> d3 isn't really designed to be used as a module, 

@mbostock and friends have gone to the trouble of ensuring that d3 is a good citizen of all _n_ ecosystems of module loaders, packing techniques, cdns, testing frameworks, etc. this is why javascript can't have nice things :crying_cat_face:

there has been some discussion about [exactly this topic](https://groups.google.com/forum/#!msg/d3-js/VaRDXom79Uc/dRRnDDGKiBAJ) on the developer list, more feedback welcome!

> but rather as a page global, 

d3 works fine in node against jsdom, no window global there! if you use d3 in a browser where requirejs or such is employed, it will not attach to the window at all! i bring this up as the ipython notebook, where i have started playing some with textures, indeed does use requirejs... which means modules coded to work exclusively with globals need extra care.luckily textures sidesteps this entirely by just using the selection api... but I do have to shim it in because of the global. the umd pattern would solve this, though (#6).

> so in this case I would not recommend listing it in package.json in any way

i suppose the argument here is that it could work with some other thing that implemented the d3 selection API... but i don't see how undocumented dependencies really help anyone!

**Comment by maxogden** [comment]
@bollwyvl Sorry, my intent wasn't to try and start a big argument here. I have used peer dependencies in the past in a few projects and have been bit by them in the long term. This is why `npm` has been de-emphasizing them over time. Here's a thread with more detail: https://github.com/npm/npm/issues/5080#issuecomment-40545599

My comment about d3 being designed for use as a page global wasn't meant as a derogatory comment towards the maintainers effort to publish d3 through many channels, which I think is awesome. What I was trying to say was there are small modules such as http://npmjs.org/ndarray that work well in a peer dep scenario as it is essentially a data structure that you are passing around between peers, and as long as the ndarray data API doesn't break it works. But for larger "kitchen-sink" style *libraries* (as opposed to *modules*), I've seen peer dependencies cause more breakage and headache to users than if they aren't there in the first place. Plus these larger libraries tend to care more about backwards compat, and additionally tend to be so large that you would never want more than one instance inside a e.g. browserify bundle anyway.

In my own personal experience it's easier to simply have the user include `d3

**Comment by maxogden** [comment]
@riccardoscalco excellent, I added you as an owner on npm. the tl;dr of maintaining is:

- run `npm version patch` if you make a non-breaking bug fix. this will increment your package.json version and also commit to git and tag the commit with the version.
- run `npm version minor` if you add new functionality (e.g. add a method to the publci API)
- run `npm version major` if you remove/break functionality. this is the most important one to remember to do

then you just `npm publish`

**Comment by bollwyvl** [comment]
@maxogden that is the bruiser of a thread. i believe the pain peerDependencies can cause: but from a discoverable metadatata standpoint, what are our options? one of the big weaknesses of onboarding d3 developers right now is that the ecosystem is invisible. it has a billion interesting examples, but no cohesive way to organize them: npm is spammed with individual methods extracted from d3 years ago, and chart libraries that make it "easy to use d3" or things that use d3.

i've proposed bower as the better target for precisely this reason, but with great bower.. :ducks:

**Comment by maxogden** [comment]
@bollwyvl you've raised some great questions. I think graphics/dataviz is a ridiculously difficult thing to modularize, because aesthetics/look and feel are so important to the final product. For example, making a reusable X/Y bar chart component means taking into account colors, fonts/text placement, proportion and lots of other things that computers aren't good at automating.

Most of the time it's easier to do it by hand. I know a lot of people who have learned JS because of d3, and they aren't the type of developers who are going to be wanting to muck about in nested node_modules folders sending upstream PRs to deps to make them e.g. more composable/expose inner options etc.

My theory is, for reasons like the ones I've listed above we have an ecosystem where it's easier to simply drop d3 in to a page as the singular dependency and then everything else is application code. The size and scope of d3 today makes it prohibitive (in my opinion) as a module dependency, but it is fine as an application dependency.

I'm not trying to make any suggestions here, more just trying to classify the problems to help shed light on which types of solutions might possible be applicable.

**Comment by riccardoscalco** [comment]
@maxogden thanks for the hints :)

**Pull request merged**
